version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 cp ./out/ s3://ingenious.website/ --recursive

artifacts:
  files: '**/*'

