import Head from "next/head";
import { Inter } from "@next/font/google";
import Swal from "sweetalert2";
import {
  Box,
  Button,
  Flex,
  Heading,
  HStack,
  Image,
  Text,
  VStack,
  Wrap,
} from "@chakra-ui/react";
import Slider from "../components/Slider";
import Scroll from "@/components/scroll";
import React, { useRef, useState } from "react";
import emailjs from "@emailjs/browser";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const form = useRef(null);
  const [isLoading, setIsLoading] = useState(false);

  const sendEmail = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      await emailjs.sendForm(
        "service_atg1icd",
        "template_l8q3h89",
        form.current,
        "WPPCF5HdenFECnXro"
      );
      Swal.fire("Successfull!", "Your mail has been delivered!", "success");
      form.current.reset();
    } catch (error) {
      Swal.fire({
        icon: "error",
        title: "Oops...",
        text: "Something went wrong!",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const section2 = {
    bgImage: "url(be-spoke.png)",
    h: { base: "100vh", md: "190vh" },
    bgSize: "120% 50%",
    bgRepeat: "no-repeat",
    bgPosition: "center",
    alignItems: "center",
    overflow: "hidden",
  };

  const section2Context = {
    spacing: "20px",
    p: { base: "10px", sm: "20px", md: "50px", lg: "100px" },

    overflow: "auto",
  };

  const section3 = {
    bgImage: "url(about-us-1.png)",
    h: "",
    bgSize: "100%, 100%",
    bgRepeat: "no-repeat",
    bgPos: "center",

    alignItems: "center",
    overflow: "",
  };

  const services = {
    bgImage: "url(file-1.png)",
    bgSize: "100% 100%",
    bgRepeat: "no-repeat",
    bgPos: "center",
    w: "650px",
    h: "450px",
    p: { base: "15", sm: "20", md: "15", lg: "20" },
    pt: { base: "20", sm: "20", md: "15", lg: "20" },
    _hover: { bgImage: "url(file-3.png)" },
  };

  const section5 = {
    bgGradient: "linear(to-b,  rgb(27,82,125), transparent)",
    borderRadius: "40px",
    h: "",
    bgSize: "100% 100%",
    alignItems: "center",
    overflow: "",
  };
  const contact_fields = {
    borderRadius: "50px",
    borderColor: "#149BE7",
    mb: "7",
  };
  return (
    <>
      <Head>
        <title>Ingenious Technologies</title>
        <meta name="description" content="Generated by create next app" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-2 overflow-hidden overflow-x-hidden bg-body">
        <div className=" flex items-center justify-center lg:h-[100vh] h-[100vh]">
          <Image src="/ingenious-1.svg" alt="INGENIOUS" w="40vw"></Image>
        </div>

        <Scroll />

        <Flex
          sx={section2}
          className="w-[100%] mx-auto md:w-[80%] md:h-[100vh] "
        >
          <VStack sx={section2Context} margin="auto">
            <p className=" text-[24px] md:text-[32px] text-[#73D0FF] max-w-md font-bold ">
              {" "}
              Bespoke solutions for your unique business needs
            </p>

            <div className="max-w-sm text-sm ">
              We partner with entrepreneurs, businesses, and organizations to
              produce impressive results.
            </div>

            <HStack
              justifyContent="right"
              spacing={{ base: "5px", sm: "10px" }} // Adjust spacing between buttons
              direction={{ base: "column", sm: "row" }} // Stack buttons vertically for extra small screens
            >
              <Button
                borderRadius="40px"
                bgGradient="linear(to-tr, #0092E3, #86D1FC)"
                px={{ base: "20px", sm: "30px" }} // Adjust padding for buttons
              >
                Try for free
              </Button>
              <Button
                borderRadius="40px"
                variant="outline"
                borderColor="#0191E3"
                px={{ base: "20px", sm: "30px" }} // Adjust padding for buttons
              >
                Learn More
              </Button>
            </HStack>
          </VStack>
        </Flex>
        <Box sx={section3}>
          <VStack direction="column">
            <Box w="400px" alignSelf="flex-end">
              <Image
                src="/team.png"
                alt="Team inage"
                className=" md:w-[25vw]"
              ></Image>
              <div className="max-w-sm text-center lg:text-sm">
                Our team of experienced professionals has a deep understanding
                of the latest trends and technologies in the industry. We work
                closely with our clients to develop customized strategies and
                solutions that are tailored to their specific needs and goals.
                Whether you're a small business looking to streamline your
                operations, or a large enterprise seeking to modernize your IT
                infrastructure, we have the skills and experience to deliver
                results.
              </div>
            </Box>
            <VStack w="500px" flex="1" textAlign="center" alignItems="center">
              <Image
                src="/ingenious.png"
                alt="INGENIOUS"
                className=" md:w-[25vw] w-[50vw] mt-20 md:mt-0"
              ></Image>
              <div className="max-w-sm text-center lg:text-sm">
                Ingenious Technology is a full-service technology solutions
                provider, delivering a wide range of services to help businesses
                thrive in today's fast-paced digital world. From IT consulting
                and managed services to software development and cybersecurity,
                we offer the expertise and resources to support our clients'
                technology needs at every stage of their business journey.
              </div>
            </VStack>

            <Box alignSelf="flex-start" w="400px" className=" mt-">
              <Image
                src="/laptop.png"
                alt="INGENIOUS"
                className=" md:w-[25vw] w-[50%] mx-auto md:mx-0  mt-20 md:mt-0"
              ></Image>
              <div className="max-w-sm text-center lg:text-sm">
                At Ingenious Technology, we believe that technology should be a
                strategic asset, not a burden. That's why we focus on delivering
                solutions that are both effective and affordable, so our clients
                can stay competitive and achieve their business objectives. We
                pride ourselves on our ability to deliver quality work on time
                and within budget, while providing exceptional customer service
                and support.
              </div>
            </Box>
          </VStack>
        </Box>
        <Box py={10} textAlign="center">
          <Heading fontSize="4vw" color="#73D0FF" mb="40px">
            Services
          </Heading>
          <Wrap spacing="20px" justify="center" pos="relative">
            <Flex sx={services}>
              <VStack alignItems="left" textAlign="left" top="40px">
                <HStack spacing=" 50px">
                  <Image
                    src="/itservices.png"
                    alt="IT consulting"
                    w="50px"
                    h="50px"
                  ></Image>
                  <Text color="#73D0FF" fontWeight="Bold">
                    IT consulting and strategy development
                  </Text>
                </HStack>
                <Text>
                  We work closely with clients to understand their business
                  objectives and develop a technology strategy to support those
                  goals. An IT consultant may provide guidance on infrastructure
                  design, system optimization, software selection, and more.
                </Text>
              </VStack>
            </Flex>
            <Flex sx={services} pos="relative">
              <VStack
                alignItems="left"
                textAlign="left"
                top="40px"
                spacing="50px"
              >
                <HStack spacing="100px">
                  <Image
                    src="/cloud.png"
                    alt="IT consulting"
                    w="50px"
                    h="50px"
                  ></Image>
                  <Text color="#73D0FF" fontWeight="Bold">
                    Cloud migration and management
                  </Text>
                </HStack>
                <Text>
                  We help businesses move their IT systems and applications to
                  the cloud by assessing a company's existing infrastructure,
                  selecting the right cloud provider and services, and migrating
                  data and applications to the cloud. We also provide ongoing
                  management and support for cloud-based systems, ensuring
                  optimal performance, security, and scalability.
                </Text>
              </VStack>
            </Flex>
            <Flex sx={services}>
              <VStack
                alignItems="left"
                textAlign="left"
                top="40px"
                spacing="50px"
              >
                <HStack spacing="100px">
                  <Image
                    src="/managed.png"
                    alt="Managed IT services"
                    w="50px"
                    h="50px"
                  ></Image>
                  <Text color="#73D0FF" fontWeight="Bold">
                    Managed IT service
                  </Text>
                </HStack>
                <Text>
                  These services include ongoing monitoring and management of a
                  company's IT infrastructure, including servers, networks,
                  cctv, unified communications and devices. Managed IT services
                  providers typically offer help desk support, disaster recovery
                  services, and cloud solutions.
                </Text>
              </VStack>
            </Flex>
            <Flex sx={services} pos="relative" top="40px">
              <VStack alignItems="left" textAlign="left" spacing="50px">
                <HStack spacing="100px">
                  <Image
                    src="/software.png"
                    alt="Software development"
                    w="50px"
                    h="50px"
                  ></Image>
                  <Text color="#73D0FF" fontWeight="Bold">
                    Custom software development and application integration
                  </Text>
                </HStack>
                <Text>
                  We create customized software solutions to meet a company's
                  specific needs. This may include building new applications,
                  integrating existing systems, or developing mobile apps.
                </Text>
              </VStack>
            </Flex>
            <Flex top="40px" pos="relative" sx={services}>
              <VStack
                alignItems="left"
                textAlign="left"
                top="40px"
                spacing="50px"
              >
                <HStack spacing="100px" top="40px">
                  <Image
                    src="/data.png"
                    alt="Data Analysis"
                    w="50px"
                    h="50px"
                  ></Image>
                  <Text color="#73D0FF" fontWeight="Bold">
                    Data analytics and business intelligence
                  </Text>
                </HStack>
                <Text>
                  This service involves leveraging data to gain insights and
                  inform business decisions. This may include designing and
                  implementing data warehouses, creating dashboards and reports,
                  and conducting data analysis to identify trends and patterns.
                </Text>
              </VStack>
            </Flex>
            <Flex sx={services} pos="relative" top="40px" zIndex={2}>
              <VStack
                alignItems="left"
                textAlign="left"
                top="40px"
                spacing="50px"
              >
                <HStack spacing="100px" top="40px">
                  <Image
                    src="/cyber.png"
                    alt="Cyber Security"
                    w="50px"
                    h="50px"
                  ></Image>
                  <Text color="#73D0FF" fontWeight="Bold">
                    Cybersecurity services
                  </Text>
                </HStack>
                <Text>
                  We help clients protect their systems, data, and networks from
                  cyber threats. This may include conducting security risk
                  assessments, implementing firewalls and intrusion detection
                  systems, and providing ongoing threat monitoring and response.
                </Text>
              </VStack>
            </Flex>
          </Wrap>
        </Box>
        <Box py={10} textAlign="center" w="100%">
          <Heading fontSize="4vw" color="#73D0FF" mb="40px">
            Products and Solutions
          </Heading>

          <Slider />
        </Box>
        <Box sx={section5}>
          <Heading
            fontSize="4vw"
            color="#73D0FF"
            mb="40px"
            textAlign="center"
            mt="20px"
          >
            Get In Touch With US
          </Heading>
          <form
            ref={form}
            onSubmit={sendEmail}
            className="max-w-screen-xl p-6 mx-auto bg-white rounded-md shadow-md md:p-12"
          >
            <div className="space-y-6">
              <div className="flex flex-col">
                <label
                  htmlFor="full_name"
                  className="font-medium text-gray-700"
                >
                  Full Name
                </label>
                <input
                  type="text"
                  id="full_name"
                  name="full_name"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                />
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="email"
                  className="mt-4 font-medium text-gray-700"
                >
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                />
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="phone_no"
                  className="mt-4 font-medium text-gray-700"
                >
                  Phone no.
                </label>
                <input
                  type="text"
                  id="phone_no"
                  name="phone_no"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                />
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="product_or_service"
                  className="mt-4 font-medium text-gray-700"
                >
                  What product or service do you want to contact us?
                </label>
                <select
                  id="product_or_service"
                  name="product_or_service"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                >
                  <option>Ingenious AMS</option>
                  <option>Nature's Buddy Smart Pot (Coming Soon)</option>
                  <option>Hospital Managment System</option>
                  <option>EMS</option>
                </select>
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="registering_as"
                  className="mt-4 font-medium text-gray-700"
                >
                  Are you registering on behalf of a business or as an
                  individual?
                </label>
                <select
                  id="registering_as"
                  name="registering_as"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                >
                  <option>YES</option>
                  <option>NO</option>
                </select>
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="business_type"
                  className="mt-4 font-medium text-gray-700"
                >
                  What type of business do you want to have with Ingenious AMS?
                </label>
                <select
                  id="business_type"
                  name="business_type"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                >
                  <option>
                    Asset Manager (Description: You own or the Asset manager of
                    the Asset)
                  </option>
                  <option>
                    Facility Manager (Description: You manager or the company
                    you work for manages an Asset)
                  </option>
                  <option>
                    Collaborator (Description: You are a service provider that
                    wants to integrate with Ingenious)
                  </option>
                </select>
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="assets_type"
                  className="mt-4 font-medium text-gray-700"
                >
                  What type of Assets do you want to onboard into Ingenious AMS
                  (With a unit counter in front of each Assets)?
                </label>
                <select
                  id="assets_type"
                  name="assets_type"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                >
                  <option>Real Estate</option>
                  <option>Hotel</option>
                  <option>Mall</option>
                  <option>Warehouse</option>
                </select>
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="preferred_communication"
                  className="mt-4 font-medium text-gray-700"
                >
                  What is your preferred means of communication?
                </label>
                <select
                  id="preferred_communication"
                  name="preferred_communication"
                  className="px-4 py-2 text-black border border-blue-500 rounded-full focus:outline-none focus:border-blue-700"
                >
                  <option className="text-black">Email</option>
                  <option className="text-black">Phone call</option>
                </select>
              </div>

              <button
                type="submit"
                className={`block px-6 py-3 mx-auto text-white transition duration-300 rounded-md ${
                  isLoading
                    ? "bg-gray-500 cursor-not-allowed"
                    : "bg-teal-500 hover:bg-teal-600"
                }`}
                disabled={isLoading}
              >
                {isLoading ? "Submitting..." : "Submit"}
              </button>
            </div>
          </form>
        </Box>
      </main>
    </>
  );
}
